name: "Sungrow Solar"
description: "Monitor your Sungrow solar inverter and battery via iSolarCloud"
version: "0.1.0"
slug: "sungrow-solar"
init: false
arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto

ingress: true
ingress_port: 3000
ingress_stream: true

panel_icon: "mdi:solar-power"
panel_title: "Sungrow Solar"

options:
  appkey: ""
  secret_key: ""
  authorize_url: ""
  redirect_url: ""
  host: "https://augateway.isolarcloud.com"
  poll_interval: 300

schema:
  appkey: str
  secret_key: password
  authorize_url: url
  redirect_url: url
  host: list(https://gateway.isolarcloud.com|https://gateway.isolarcloud.com.hk|https://gateway.isolarcloud.eu|https://augateway.isolarcloud.com)
  poll_interval: int(60,600)
