name: "Sungrow Solar"
description: "Monitor your Sungrow solar inverter and battery via iSolarCloud"
version: "0.1.0"
slug: "sungrow-solar"
init: false
arch:
  - aarch64
  - amd64
  - armv7

startup: application
boot: auto

ingress: true
ingress_port: 3000
ingress_stream: true

panel_icon: "mdi:solar-power"
panel_title: "Sungrow Solar"

options:
  username: ""
  password: ""
  appkey: ""
  host: "https://augateway.isolarcloud.com"
  poll_interval: 60

schema:
  username: str
  password: password
  appkey: str
  host: url
  poll_interval: int(30,300)
